-- Schema for Mobile Legends Heroes
DROP TABLE IF EXISTS `ml_heroes`;
CREATE TABLE `ml_heroes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `role` varchar(100) NOT NULL,
  `iMago_url` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Inserting some initial heroes
INSERT INTO `ml_heroes` (`name`, `role`, `iMago_url`) VALUES
('Miya', 'Tirador', 'assets/heroes/miya.jpg'),
('Balmond', 'Combatiente/Tanque', 'assets/heroes/balmond.jpg'),
('Saber', 'Asesino', 'assets/heroes/saber.jpg'),
('Alice', 'Mago/Tanque', 'assets/heroes/alice.jpg'),
('Nana', 'Mago/Apoyo', 'assets/heroes/nana.jpg'),
('Tigreal', 'Tanque/Apoyo', 'assets/heroes/tigreal.jpg'),
('Alucard', 'Combatiente/Asesino', 'assets/heroes/alucard.jpg'),
('Karina', 'Asesino', 'assets/heroes/karina.jpg'),
('Akai', 'Tanque/Apoyo', 'assets/heroes/akai.jpg'),
('Franco', 'Tanque', 'assets/heroes/franco.jpg'),
('Bane', 'Combatiente/Mago', 'assets/heroes/bane.jpg'),
('Bruno', 'Tirador', 'assets/heroes/bruno.jpg'),
('Clint', 'Tirador', 'assets/heroes/clint.jpg'),
('Rafaela', 'Apoyo/Mago', 'assets/heroes/rafaela.jpg'),
('Eudora', 'Mago', 'assets/heroes/eudora.jpg'),
('Zilong', 'Combatiente/Asesino', 'assets/heroes/zilong.jpg'),
('Fanny', 'Asesino', 'assets/heroes/fanny.jpg'),
('Layla', 'Tirador', 'assets/heroes/layla.jpg'),
('Minotaur', 'Tanque/Apoyo', 'assets/heroes/minotaur.jpg'),
('Lolita', 'Apoyo/Tanque', 'assets/heroes/lolita.jpg'),
('Hayabusa', 'Asesino', 'assets/heroes/hayabusa.jpg'),
('Freya', 'Combatiente', 'assets/heroes/freya.jpg'),
('Gord', 'Mago', 'assets/heroes/gord.jpg'),
('Natalia', 'Asesino', 'assets/heroes/natalia.jpg'),
('Kagura', 'Mago', 'assets/heroes/kagura.jpg'),
('Chou', 'Combatiente', 'assets/heroes/chou.jpg'),
('Sun', 'Combatiente', 'assets/heroes/sun.jpg'),
('Alpha', 'Combatiente', 'assets/heroes/alpha.jpg'),
('Ruby', 'Combatiente/Tanque', 'assets/heroes/ruby.jpg'),
('Yi Sun-shin', 'Asesino/Tirador', 'assets/heroes/yi_sun_shin.jpg'),
('Moskov', 'Tirador', 'assets/heroes/moskov.jpg'),
('Johnson', 'Tanque/Apoyo', 'assets/heroes/johnson.jpg'),
('Cyclops', 'Mago', 'assets/heroes/cyclops.jpg'),
('Estes', 'Apoyo', 'assets/heroes/estes.jpg'),
('Hilda', 'Combatiente/Tanque', 'assets/heroes/hilda.jpg'),
('Aurora', 'Mago', 'assets/heroes/aurora.jpg'),
('Lapu-Lapu', 'Combatiente/Asesino', 'assets/heroes/lapu_lapu.jpg'),
('Vexana', 'Mago', 'assets/heroes/vexana.jpg'),
('Roger', 'Combatiente/Tirador', 'assets/heroes/roger.jpg'),
('Karrie', 'Tirador', 'assets/heroes/karrie.jpg'),
('Gatotkaca', 'Tanque/Combatiente', 'assets/heroes/gatotkaca.jpg'),
('Argus', 'Combatiente', 'assets/heroes/argus.jpg'),
('Odette', 'Mago', 'assets/heroes/odette.jpg'),
('Lancelot', 'Asesino', 'assets/heroes/lancelot.jpg'),
('Diggie', 'Apoyo', 'assets/heroes/diggie.jpg'),
('Hylos', 'Tanque/Apoyo', 'assets/heroes/hylos.jpg'),
('Zhask', 'Mago', 'assets/heroes/zhask.jpg'),
('Helcurt', 'Asesino', 'assets/heroes/helcurt.jpg'),
('Pharsa', 'Mago', 'assets/heroes/pharsa.jpg'),
('Lesley', 'Tirador/Asesino', 'assets/heroes/lesley.jpg'),
('Jawhead', 'Combatiente', 'assets/heroes/jawhead.jpg'),
('Angela', 'Apoyo', 'assets/heroes/angela.jpg'),
('Gusion', 'Asesino/Mago', 'assets/heroes/gusion.jpg'),
('Valir', 'Mago', 'assets/heroes/valir.jpg'),
('Martis', 'Combatiente', 'assets/heroes/martis.jpg'),
('Uranus', 'Tanque', 'assets/heroes/uranus.jpg'),
('Hanabi', 'Tirador', 'assets/heroes/hanabi.jpg'),
('Chang\'e', 'Mago', 'assets/heroes/change.jpg'),
('Kaja', 'Apoyo/Combatiente', 'assets/heroes/kaja.jpg'),
('Selena', 'Asesino/Mago', 'assets/heroes/selena.jpg'),
('Aldous', 'Combatiente', 'assets/heroes/aldous.jpg'),
('Claude', 'Tirador', 'assets/heroes/claude.jpg'),
('Vale', 'Mago', 'assets/heroes/vale.jpg'),
('Leomord', 'Combatiente', 'assets/heroes/leomord.jpg'),
('Lunox', 'Mago', 'assets/heroes/lunox.jpg'),
('Hanzo', 'Asesino', 'assets/heroes/hanzo.jpg'),
('Belerick', 'Tanque/Apoyo', 'assets/heroes/belerick.jpg'),
('Kimmy', 'Tirador/Mago', 'assets/heroes/kimmy.jpg'),
('Thamuz', 'Combatiente', 'assets/heroes/thamuz.jpg'),
('Harith', 'Mago', 'assets/heroes/harith.jpg'),
('Minsitthar', 'Combatiente', 'assets/heroes/minsitthar.jpg'),
('Kadita', 'Mago/Asesino', 'assets/heroes/kadita.jpg'),
('Badang', 'Combatiente', 'assets/heroes/badang.jpg'),
('Guinevere', 'Combatiente/Mago', 'assets/heroes/guinevere.jpg'),
('Granger', 'Tirador', 'assets/heroes/granger.jpg'),
('Khufra', 'Tanque/Apoyo', 'assets/heroes/khufra.jpg'),
('Esmeralda', 'Mago/Tanque', 'assets/heroes/esmeralda.jpg'),
('Terizla', 'Combatiente', 'assets/heroes/terizla.jpg'),
('X.Borg', 'Combatiente', 'assets/heroes/xborg.jpg'),
('Ling', 'Asesino', 'assets/heroes/ling.jpg'),
('Dyrroth', 'Combatiente', 'assets/heroes/dyrroth.jpg'),
('Lylia', 'Mago', 'assets/heroes/lylia.jpg'),
('Baxia', 'Tanque', 'assets/heroes/baxia.jpg'),
('Masha', 'Combatiente/Tanque', 'assets/heroes/masha.jpg'),
('Wanwan', 'Tirador', 'assets/heroes/wanwan.jpg'),
('Silvanna', 'Combatiente/Mago', 'assets/heroes/silvanna.jpg'),
('Cecilion', 'Mago', 'assets/heroes/cecilion.jpg'),
('Carmilla', 'Apoyo/Tanque', 'assets/heroes/carmilla.jpg'),
('Atlas', 'Tanque/Apoyo', 'assets/heroes/atlas.jpg'),
('Popol and Kupa', 'Tirador', 'assets/heroes/popol_kupa.jpg'),
('Yu Zhong', 'Combatiente', 'assets/heroes/yuzhong.jpg'),
('Luo Yi', 'Mago/Apoyo', 'assets/heroes/luoyi.jpg'),
('Benedetta', 'Asesino/Combatiente', 'assets/heroes/benedetta.jpg'),
('Khaleed', 'Combatiente', 'assets/heroes/khaleed.jpg'),
('Barats', 'Tanque/Combatiente', 'assets/heroes/barats.jpg'),
('Brody', 'Tirador', 'assets/heroes/brody.jpg'),
('Yve', 'Mago', 'assets/heroes/yve.jpg'),
('Mathilda', 'Apoyo/Asesino', 'assets/heroes/mathilda.jpg'),
('Paquito', 'Combatiente', 'assets/heroes/paquito.jpg'),
('Gloo', 'Tanque/Apoyo', 'assets/heroes/gloo.jpg'),
('Beatrix', 'Tirador', 'assets/heroes/beatrix.jpg'),
('Phoveus', 'Combatiente', 'assets/heroes/phoveus.jpg'),
('Natan', 'Tirador', 'assets/heroes/natan.jpg'),
('Aulus', 'Combatiente', 'assets/heroes/aulus.jpg'),
('Floryn', 'Apoyo', 'assets/heroes/floryn.jpg'),
('Valentina', 'Mago', 'assets/heroes/valentina.jpg'),
('Edith', 'Tanque/Tirador', 'assets/heroes/edith.jpg'),
('Yin', 'Combatiente/Asesino', 'assets/heroes/yin.jpg'),
('Melissa', 'Tirador', 'assets/heroes/melissa.jpg'),
('Xavier', 'Mago', 'assets/heroes/xavier.jpg'),
('Julian', 'Combatiente/Mago', 'assets/heroes/julian.jpg'),
('Fredrinn', 'Tanque/Combatiente', 'assets/heroes/fredrinn.jpg'),
('Joy', 'Asesino', 'assets/heroes/joy.jpg'),
('Novaria', 'Mago', 'assets/heroes/novaria.jpg'),
('Arlott', 'Combatiente/Asesino', 'assets/heroes/arlott.jpg'),
('Ixia', 'Tirador', 'assets/heroes/ixia.jpg'),
('Nolan', 'Asesino', 'assets/heroes/nolan.jpg'),
('Cici', 'Combatiente', 'assets/heroes/cici.jpg'),
('Chip', 'Apoyo/Tanque', 'assets/heroes/chip.jpg'),
('Suyou', 'Asesino/Combatiente', 'assets/heroes/suyou.jpg');
